apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-atry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-atry
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-atry
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-atry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-atry
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fpnc-tenant/rhtap-demo-app/hacbs-test-project-atry@sha256:a279910d7e49d279a152c8ecda088c47ccffd6e84c5e8a9f8622ab42d7e35935
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
